#!/bin/bash

set -e

function print-banner () {
    local message="$1"
    echo "##################################"
    echo "$message"
    echo "##################################"
}

print-banner "Input Grafana Host and Port"
read -p "Enter Grafana Hostname (with http://): " host
read -p "Enter Grafana Port: " port
export grafana_host="$host" 
export grafana_port="$port"

print-banner "Input Grafana Username and Password"
read -p "Enter Grafana Username (default admin): " user
read -p "Enter Grafana Password (default admin): " pass
export grafana_user="$user" 
export grafana_pass="$pass"

print-banner "Input influxdb Host and Port"
read -p "Enter influxdb Hostname: " host
read -p "Enter influxdb Port (default 8086): " port
export influxdb_host="$host" 
export influxdb_port="$port"

print-banner "Input influxdb Username and Password"
read -p "Enter influxdb Username: " user
read -p "Enter influxdb Password: " pass
export influxdb_user="$user" 
export influxdb_pass="$pass"

./temp/grafana-conf-datasource-api