#!/bin/bash

set -e

function print-banner () {
    local message="$1"
    echo "##################################"
    echo "$message"
    echo "##################################"
}

print-banner "Input Grafana Host and Port"
read -p "Enter Grafana Hostname": grafana_host
read -p "Enter Grafana Port": grafana_port
export "$grafana_host" 
export "$grafana_port"

print-banner "Input Grafana Username and Password"
read -p "Enter Grafana Username (default admin)": grafana_user
read -p "Enter Grafana Password (default admin)": grafana_password
export "$grafana_user" 
export "$grafana_pass"

print-banner "Input influxdb Host and Port"
read -p "Enter influxdb Hostname": influxdb_host
read -p "Enter influxdb Port (default 8086)": influxdb_port
export "$influxdb_host" 
export "$influxdb_port"

print-banner "Input influxdb Username and Password"
read -p "Enter influxdb Username": influxdb_user
read -p "Enter influxdb Password": influxdb_password
export "$influxdb_user" 
export "$influxdb_pass"

./temp/conf-datasource-api