#!/bin/bash
args1="$1"

if [ "$args1" == "--help" ] || [ "$args1" == "help" ] ; then
    echo "usage:"
    echo "./install-heapster {INFLUXDB_PORT}"
else
    export INFLUXDB_PORT="$1"
    mkdir -p temp
    cp spec/heapster* temp/
    eval "echo \"$(cat spec/heapster.yaml)\"" > temp/heapster.yaml
    kubectl create -f temp/
    rm -rf temp/
fi