#!/bin/bash
args1="$1"

if [ "$args1" == "--help" ] || [ "$args1" == "help" ] ; then
    echo "usage:"
    echo "./install-grafana"
    exit 0
else
    mkdir -p temp
    cp spec/grafana* temp/
    eval "echo \"$(cat spec/grafana.yaml)\"" > temp/grafana.yaml
    kubectl create -f temp/
    ./config-influxdb-datasource
    sleep 2
    rm -rf temp/
fi